version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    ports:
      - "8080:8080"
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_KEY: base64:9ppAuTJ6huQe8jxM4YrBYCnQWtoeNGG4uyok8jZbqeI=
      DB_CONNECTION: mysql
      DB_HOST: 34.50.72.192
      DB_PORT: 3306
      DB_DATABASE: medic
      DB_USERNAME: root
      DB_PASSWORD: haku
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: haku
      MYSQL_DATABASE: medic
      MYSQL_USER: root
      MYSQL_PASSWORD: haku
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
